version: '3.4'

services:
  faq.ap:
    image: ${DOCKER_REGISTRY-}faqap
    build:
      context: .
      dockerfile: FAQ.Apı/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw