version: '3.4'

services:
  faq.ap:
    container_name: faqapi 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80" 
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
      